<?php echo $this->partial('header.phtml'); ?>
<div>
    <h1>Juez Virtual</h1>
	<h3><?php //echo $this->escape($this->title); ?></h3>
		<?php echo $this->partial('menu.phtml'); ?>
    <div>
    	<?php echo $this->form ; ?>
    	<p>no tienes cuenta como comite? create una <a href="<?php echo $this->baseUrl().'/registro/comite';?>">aqui</a></p>
		<p>llenar con un incio presentable</p>
    </div>
</div>
<?php echo $this->partial('footer.phtml'); ?>
